

# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:mysql://localhost:3306/sm_db
#      username: root
#      password: admin80
#      driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.boliu.jdbc.Driver
    druid:
      master:
        url: jdbc:boliu://127.0.0.1:7015;127.0.0.1:7007;127.0.0.1:7006
        username: 系统管理员
        password: root123!
      validationQuery: select 1 as 1 from 保留区块0


# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.cchu.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: news_ # 设置表的前缀

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义

logging:
  level:
    org.springframework: INFO
